# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d41fd4e055ab89097f2aa4385ad5b69c69e351f24fa4f8a2324da9ecf3a2ca4ec9b3b5f49dffd03ebc97408aebcc6c4e0ab890669b78c5c81d6e278e7001058d

test:
  secret_key_base: 643e54676e1bcd1b4e955ac30f1893df94eb4863f6949eaa4c8a0153c4de4e27d4d0ea9158b0446d0b5babca25a4abcb354997598ef2d305416e64ad29454e1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
